@echo off
echo Killing existing Next.js processes...
taskkill /F /IM node.exe /T 2>nul
timeout /t 2 /nobreak >nul
echo Deleting lock file...
if exist ".next\dev\lock" del /f ".next\dev\lock"
echo Starting dev server...
npm run dev
